name: Testing and Static Analysis

on:
  push:
    branches:
      - 'main'

jobs:
  laravel-tests:
    name: Laravel unit and feature testing
    runs-on: ubuntu-latest

    steps:
      name: Checkout
      uses: actions/checkout@v2

    - name: Configure PHP 8.1          
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/pest

  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      name: Checkout
      uses: actions/checkout@v2

    - name: Configure PHP 8.1
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'

    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run phpstan
      run: vendor/bin/phpstan analyse --ansi